#!/bin/sh
# Auto-generated JTAG burn script
# DO NOT EDIT MANUALLY - Generated by script

# Important parameter notes:
# Need modify this according to your IP and DebugServer port
# target remote localhost:3333
# set *0x18020800 = 0x100000    : enable syscfg cmu
# set *0x18000160 = 0xA1C00000 : disable tcm
# set $mitcmcr=0                : disable tcm
# set $mdtcmcr=0                : disable tcm
# a0=0x9 : set jtag burn flag
# a2 = 0x30054100 : the application.aic load to sram(0x30054100), this is burn into flash data.
# a3 = 0 : flash save offset
# a4 = 108304 : the application.aic size
# a5 = 0 : burn after reboot or not flag
# usually customer just to modify a4 register to compatible.

# Warning messages:
echo "Warning: Target file not found D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/Debug/pdata.bin"

# Initialize JTAG interface
reset

# Disable TCM for programming
set *0x18020800 = 0x100000
set *0x18000160 = 0xA1C00000
set $mitcmcr=0
set $mdtcmcr=0

# Burn spl partition with bootloader.aic
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/flash/JtagBurn.bin binary 0x30044100
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/Debug/bootloader.aic binary 0x30054100
set $a0=0x9
set $a2=0x30054100
set $a3=0x0
set $a4=0x10000
set $a5=0
set $pc=0x30044100
c

# Burn uploader partition with uploader.aic
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/flash/JtagBurn.bin binary 0x30044100
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/Debug/uploader.aic binary 0x30054100
set $a0=0x9
set $a2=0x30054100
set $a3=0x11000
set $a4=0x40000
set $a5=0
set $pc=0x30044100
c

# Burn app1 partition with application.aic
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/flash/JtagBurn.bin binary 0x30044100
restore D:/eclipse/eclipse/neworkspace/AIC_M7000_SH_Kit_New/Debug/application.aic binary 0x30054100
set $a0=0x9
set $a2=0x30054100
set $a3=0x51000
set $a4=0x100000
set $a5=1
set $pc=0x30044100
c
