/*
 * Copyright (c) 2022-2023, ArtInChip Technology Co., Ltd
 *
 */
#ifndef INCLUDE_HAL_CMU_TLB_H_
#define INCLUDE_HAL_CMU_TLB_H_


#define CMU_CLK_FRA1			CMU_CLK_DIS
#define CMU_CLK_AHB0			CMU_CLK_AXI0
#define CMU_CLK_APB1			CMU_CLK_24M
#define CMU_CLK_APB2			CMU_CLK_DIS
#define CMU_CLK_DDR				CMU_CLK_DIS

typedef enum cmu_clk_id_e
{
    CMU_CLK_DIS = 0,
    CMU_CLK_24M,
    CMU_CLK_32K,
    CMU_CLK_INT0,
    CMU_CLK_INT1,
    CMU_CLK_FRA0,
    CMU_CLK_FRA2,
    CMU_CLK_AXI0,
    CMU_CLK_APB0,
    CMU_CLK_CPU,
    CMU_CLK_PRE_DIV0,
    CMU_CLK_PRE_DIV2,
    CMU_CLK_SCLK,
    CMU_CLK_PIXCLK,
    CMU_CLK_AUD,
    CMU_CLK_PWMCS,
    // CMU_CLK_XPWM			,
    CMU_CLK_GPT,
} cmu_clk_id_t;

#define CMU_MOD_USB_HOST0		CMU_MOD_DIS
#define	CMU_MOD_USB_PHY0		CMU_MOD_DIS
#define	CMU_MOD_USB_PHY1		CMU_MOD_DIS
#define CMU_MOD_GMAC0			CMU_MOD_EMAC
#define CMU_MOD_GMAC1			CMU_MOD_DIS
#define CMU_MOD_SDMC2 			CMU_MOD_DIS
#define CMU_MOD_I2S0           		CMU_MOD_I2S0
#define CMU_MOD_I2S1           		CMU_MOD_I2S1
#define CMU_MOD_MDI       		CMU_MOD_DIS
#define CMU_MOD_CIR			CMU_MOD_DIS
#define CMU_MOD_AUDIO			CMU_MOD_DIS
#define CMU_MOD_LCD			CMU_MOD_DIS
#define CMU_MOD_LVDS			CMU_MOD_DIS
#define CMU_MOD_MIPI_DSI		CMU_MOD_DIS
#define CMU_MOD_DE			CMU_MOD_DIS
#define CMU_MOD_VE			CMU_MOD_DIS
#define CMU_MOD_GE			CMU_MOD_DIS
#define CMU_MOD_PWM			CMU_MOD_DIS
#define CMU_MOD_RTP			CMU_MOD_DIS
#define CMU_MOD_GPAI			CMU_MOD_DIS
#define CMU_MOD_ADCIM			CMU_MOD_DIS
#define CMU_MOD_DMA0				CMU_MOD_DMA0
#define CMU_MOD_DMA1				CMU_MOD_DMA1
#define CMU_MOD_R_WDOG			CMU_MOD_DIS
#define CMU_MOD_DDR_CTRL		CMU_MOD_DIS
#define CMU_MOD_DVP			CMU_MOD_DIS
#define CMU_MOD_RTC			CMU_MOD_DIS
#define CMU_MOD_CAN1			CMU_MOD_DIS

#define PRCM_CLK_APB0			CMU_CLK_APB1
#define PRCM_CLK_APB1			CMU_MOD_DIS
#define PRCM_CLK_AXI			CMU_MOD_DIS
#define PRCM_CLK_AHB			CMU_MOD_DIS

typedef enum cmu_mod_id_e
{
    CMU_MOD_DIS = 0,
    CMU_MOD_WDOG,
    CMU_MOD_PWM0,
    CMU_MOD_PWM1,
    CMU_MOD_PWM2,
    CMU_MOD_PWM3,
    CMU_MOD_PWM4,
    CMU_MOD_PWM5,
    CMU_MOD_DMA0,
    CMU_MOD_DMA1,
    CMU_MOD_DCE,
    CMU_MOD_CE,
    CMU_MOD_USB_FS_DR,
    CMU_MOD_USB_FS_DR_PHY,
    CMU_MOD_EMAC,
    CMU_MOD_CANFD0,
    CMU_MOD_CANFD1,
    CMU_MOD_CAN0,
    CMU_MOD_XSPI,
    CMU_MOD_SPI0,
    CMU_MOD_SPI1,
    CMU_MOD_SPI2,
    CMU_MOD_SPI3,
    CMU_MOD_SPI4,
    CMU_MOD_SPI5,
    CMU_MOD_SDMC0,
    CMU_MOD_CORDIC,
    CMU_MOD_HCL,
    CMU_MOD_RDC,
    CMU_MOD_PFM,
    CMU_MOD_PBUS,
    CMU_MOD_FFT,
    CMU_MOD_SYSCFG,
    CMU_MOD_SPI_ENC,
    CMU_MOD_PWMCS,
    CMU_MOD_ADC,
    CMU_MOD_I2S0,
    CMU_MOD_I2S1,
    CMU_MOD_GPIO,
    CMU_MOD_UART0,
    CMU_MOD_UART1,
    CMU_MOD_UART2,
    CMU_MOD_UART3,
    CMU_MOD_UART4,
    CMU_MOD_UART5,
    CMU_MOD_UART6,
    CMU_MOD_UART7,
    CMU_MOD_UART8,
    CMU_MOD_TA_IF,
    CMU_MOD_EDT_IF,
    CMU_MOD_BISS_IF,
    CMU_MOD_SDFM,
    //CMU_MOD_DVP			,
    CMU_MOD_SID,
    CMU_MOD_GTC,
    CMU_MOD_I2C0,
    CMU_MOD_I2C1,
    CMU_MOD_I2C2,
    CMU_MOD_I2C3,
    CMU_MOD_THS,
    CMU_MOD_VS,
    CMU_MOD_CPM,
    CMU_MOD_PGA,
    CMU_MOD_GPT0,
    CMU_MOD_GPT1,
    CMU_MOD_GPT2,
    CMU_MOD_GPT3,
    CMU_MOD_EtherCAT,
} cmu_mod_id_t;

#define REG_CMU_CLK_DDR			REG_CMU_CLK_DIS
#define REG_CMU_CLK_CPU 		REG_CMU_CLK_CPU0

#define REG_CMU_PLL_INT0_GEN      	(BASE_CMU + 0x000)
#define REG_CMU_PLL_INT1_GEN      	(BASE_CMU + 0x004)
#define REG_CMU_PLL_FRA0_GEN      	(BASE_CMU + 0x020)
#define REG_CMU_PLL_FRA2_GEN      	(BASE_CMU + 0x028)
#define REG_CMU_PLL_INT0_CFG      	(BASE_CMU + 0x040)
#define REG_CMU_PLL_INT1_CFG      	(BASE_CMU + 0x044)
#define REG_CMU_PLL_FRA0_CFG      	(BASE_CMU + 0x060)
#define REG_CMU_PLL_FRA2_CFG      	(BASE_CMU + 0x068)
#define REG_CMU_PLL_FRA0_SDM      	(BASE_CMU + 0x080)
#define REG_CMU_PLL_FRA2_SDM      	(BASE_CMU + 0x088)
#define REG_CMU_PLL_COM           	(BASE_CMU + 0x0A0)
#define REG_CMU_PLL_IN            	(BASE_CMU + 0x0A4)
#define REG_CMU_PLL_OUT            	(BASE_CMU + 0x0A8)
#define REG_CMU_CNT_CLT            	(BASE_CMU + 0x0D0)
#define REG_CMU_OSC_CNT            	(BASE_CMU + 0x0D4)
#define REG_CMU_XTAL_CNT            	(BASE_CMU + 0x0D8)
#define REG_CMU_CNT_THR            	(BASE_CMU + 0x0DC)
#define REG_CMU_CLK_OUT0          	(BASE_CMU + 0x0E0)
#define REG_CMU_CLK_OUT1          	(BASE_CMU + 0x0E4)
#define REG_CMU_CLK_OUT2          	(BASE_CMU + 0x0E8)
#define REG_CMU_CLK_OUT3          	(BASE_CMU + 0x0EC)
#define REG_CMU_CLK_AXI0          	(BASE_CMU + 0x100)
#define REG_CMU_CLK_AHB0          	(BASE_CMU + 0x110)
#define REG_CMU_CLK_APB0          	(BASE_CMU + 0x120)
#define REG_CMU_CLK_CPU0		(BASE_CMU + 0x180)
#define REG_CMU_RST_ENTRY_CPU0		(BASE_CMU + 0x184)
#define REG_CMU_CLK_CPU1		(BASE_CMU + 0x190)
#define REG_CMU_RST_ENTRY_CPU1		(BASE_CMU + 0x194)
#define REG_CMU_PRE_DIV			(BASE_CMU + 0x1C0)
#define REG_CMU_CLK_WDOG          	(BASE_CMU + 0x20C)
#define REG_CMU_CLK_DISP          	(BASE_CMU + 0x220)
#define REG_CMU_CLK_DISP0_SCLK		(BASE_CMU + 0x220)
#define REG_CMU_CLK_DISP0_PIXCLK	(BASE_CMU + 0x224)
#define REG_CMU_CLK_AUD          	(BASE_CMU + 0x230)
#define REG_CMU_CLK_PWMCS_SDFM         	(BASE_CMU + 0x240)
#define REG_CMU_CLK_XPWM0          	(BASE_CMU + 0x244)
#define REG_CMU_CLK_XPWM1          	(BASE_CMU + 0x248)
#define REG_CMU_CLK_XPWM2          	(BASE_CMU + 0x24C)
#define REG_CMU_CLK_XPWM3          	(BASE_CMU + 0x250)
#define REG_CMU_CLK_XPWM4          	(BASE_CMU + 0x254)
#define REG_CMU_CLK_XPWM5          	(BASE_CMU + 0x258)

#define REG_CMU_CLK_DMA0		(BASE_CMU + 0x400)
#define REG_CMU_CLK_DMA1		(BASE_CMU + 0x404)
#define REG_CMU_CLK_DCE			(BASE_CMU + 0x414)
#define REG_CMU_CLK_CE			(BASE_CMU + 0x418)
#define REG_CMU_CLK_USB_DEV0		(BASE_CMU + 0x41C)
#define REG_CMU_CLK_USB_HOST0		(BASE_CMU + 0x420)
#define REG_CMU_CLK_USB_DEV1		(BASE_CMU + 0x424)
#define REG_CMU_CLK_USB_HOST1		(BASE_CMU + 0x428)
#define REG_CMU_CLK_USB_DR_PHY0		(BASE_CMU + 0x42C)
#define REG_CMU_CLK_USB_PHY_DEV1	(BASE_CMU + 0x430)
#define REG_CMU_CLK_USB_PHY_HOST1	(BASE_CMU + 0x434)
#define REG_CMU_CLK_USB_FS_DR		(BASE_CMU + 0x438)
#define REG_CMU_CLK_USB_FS_DR_PHY	(BASE_CMU + 0x43C)
#define REG_CMU_CLK_EMAC		(BASE_CMU + 0x440)
#define REG_CMU_CLK_CANFD0		(BASE_CMU + 0x448)//FOR CANFD
#define REG_CMU_CLK_CANFD1		(BASE_CMU + 0x44C)//FOR CANFD
#define REG_CMU_CLK_CAN0		(BASE_CMU + 0x450)//FOR CAN2.0
#define REG_CMU_CLK_XSPI		(BASE_CMU + 0x45C)
#define REG_CMU_CLK_SPI0		(BASE_CMU + 0x460)
#define REG_CMU_CLK_SPI1		(BASE_CMU + 0x464)
#define REG_CMU_CLK_SPI2		(BASE_CMU + 0x468)
#define REG_CMU_CLK_SPI3		(BASE_CMU + 0x46C)
#define REG_CMU_CLK_SPI4		(BASE_CMU + 0x470)
#define REG_CMU_CLK_SPI5		(BASE_CMU + 0x474)
#define REG_CMU_CLK_SDMC0		(BASE_CMU + 0x480)
#define REG_CMU_CLK_SDMC1		(BASE_CMU + 0x484)
#define REG_CMU_CLK_CORDIC		(BASE_CMU + 0x490)
#define REG_CMU_CLK_HCL			(BASE_CMU + 0x494)
#define REG_CMU_CLK_RDC			(BASE_CMU + 0x498)
#define REG_CMU_CLK_PFM			(BASE_CMU + 0x49C)
#define REG_CMU_CLK_PBUS		(BASE_CMU + 0x4A0)
#define REG_CMU_CLK_FFT			(BASE_CMU + 0x4A4)
#define REG_CMU_CLK_SYSCFG		(BASE_CMU + 0x800)
#define REG_CMU_CLK_SPIENC		(BASE_CMU + 0x810)
#define REG_CMU_CLK_PWMCS		(BASE_CMU + 0x814)
#define REG_CMU_CLK_PSADC		(BASE_CMU + 0x818)
#define REG_CMU_CLK_MTOP		(BASE_CMU + 0x81C)
#define REG_CMU_CLK_I2S0		(BASE_CMU + 0x820)
#define REG_CMU_CLK_I2S1		(BASE_CMU + 0x824)
#define REG_CMU_CLK_AUDIO		(BASE_CMU + 0x830)
#define REG_CMU_CLK_GPIO		(BASE_CMU + 0x83C)
#define REG_CMU_CLK_UART0		(BASE_CMU + 0x840)
#define REG_CMU_CLK_UART1		(BASE_CMU + 0x844)
#define REG_CMU_CLK_UART2		(BASE_CMU + 0x848)
#define REG_CMU_CLK_UART3		(BASE_CMU + 0x84C)
#define REG_CMU_CLK_UART4		(BASE_CMU + 0x850)
#define REG_CMU_CLK_UART5		(BASE_CMU + 0x854)
#define REG_CMU_CLK_UART6		(BASE_CMU + 0x858)
#define REG_CMU_CLK_UART7		(BASE_CMU + 0x85C)
#define REG_CMU_CLK_UART8		(BASE_CMU + 0x860)
#define REG_CMU_CLK_TA_IF		(BASE_CMU + 0x870)
#define REG_CMU_CLK_EDT_IF		(BASE_CMU + 0x874)
#define REG_CMU_CLK_BISS_IF		(BASE_CMU + 0x878)
#define REG_CMU_CLK_SDFM		(BASE_CMU + 0x87C)
#define REG_CMU_CLK_LCD			(BASE_CMU + 0x880)
#define REG_CMU_CLK_LVDS		(BASE_CMU + 0x884)
#define REG_CMU_CLK_MIPI_DSI		(BASE_CMU + 0x888)
#define REG_CMU_CLK_DVP			(BASE_CMU + 0x890)
#define REG_CMU_CLK_DE			(BASE_CMU + 0x8C0)
#define REG_CMU_CLK_GE			(BASE_CMU + 0x8C4)
#define REG_CMU_CLK_VE			(BASE_CMU + 0x8C8)
#define REG_CMU_CLK_SID			(BASE_CMU + 0x904)
#define REG_CMU_CLK_RTC			(BASE_CMU + 0x908)
#define REG_CMU_CLK_GTC			(BASE_CMU + 0x90C)
#define REG_CMU_CLK_TWI0		(BASE_CMU + 0x960)
#define REG_CMU_CLK_TWI1		(BASE_CMU + 0x964)
#define REG_CMU_CLK_TWI2		(BASE_CMU + 0x968)
#define REG_CMU_CLK_TWI3		(BASE_CMU + 0x96C)

#define REG_CMU_CLK_PWM			(BASE_CMU + 0x990)
#define REG_CMU_CLK_ADCIM		(BASE_CMU + 0x9A0)
#define REG_CMU_CLK_GPAI		(BASE_CMU + 0x9A4)
#define REG_CMU_CLK_RTP			(BASE_CMU + 0x9A8)
#define REG_CMU_CLK_THS			(BASE_CMU + 0x9AC)
#define REG_CMU_CLK_VS			(BASE_CMU + 0x9B0)
#define REG_CMU_CLK_CPM			(BASE_CMU + 0x9E4)
#define REG_CMU_CLK_PGA			(BASE_CMU + 0x9F0)
#define REG_CMU_CLK_GPT0		(BASE_CMU + 0xA00)
#define REG_CMU_CLK_GPT1		(BASE_CMU + 0xA04)
#define REG_CMU_CLK_GPT2		(BASE_CMU + 0xA08)
#define REG_CMU_CLK_GPT3		(BASE_CMU + 0xA0C)

#define REG_CMU_CLK_ESC			(BASE_CMU + 0xC00)
#define REG_CMU_CLK_DIS			(BASE_CMU + 0xEFC)

#define REG_CMU_REG_WR_CFG		(BASE_CMU + 0xFE8)
#define REG_CMU_REG_WR_DIS_STS		(BASE_CMU + 0xFEC)
#define REG_CMU_CMU_MOD_VER		(BASE_CMU + 0xFFC)


#endif /* INCLUDE_HAL_CMU_TLB_H_ */
