/*
 * cmu_tlb.c
 */
#include <all_inc.h>
//时钟源配置
const cmu_src_clk_t cmu_src_clk[] __attribute__((aligned(16))) = {
                    //  clk_reg                 clk_type            clk_para    clk_src         clk_fmax Mhz
    [CMU_CLK_DIS] =    {0,                       CMU_CLK_TYPE_OSC,   0,          CMU_CLK_DIS,     0       },
    [CMU_CLK_24M] =    {CMU_CLK_24M_FREQ,        CMU_CLK_TYPE_OSC,   0,          CMU_CLK_24M,     24      },
    [CMU_CLK_32K] =    {CMU_CLK_32K_FREQ,        CMU_CLK_TYPE_OSC,   0,          CMU_CLK_32K,     1       },
    [CMU_CLK_INT0] =   {REG_CMU_PLL_INT0_GEN,    CMU_CLK_TYPE_PLL,   0,          CMU_CLK_24M,     480     },
    [CMU_CLK_INT1] =   {REG_CMU_PLL_INT1_GEN,    CMU_CLK_TYPE_PLL,   0,          CMU_CLK_24M,     1200    },
    [CMU_CLK_FRA0] =   {REG_CMU_PLL_FRA0_GEN,    CMU_CLK_TYPE_PLL,   0,          CMU_CLK_24M,     1200    },
    [CMU_CLK_FRA2] =   {REG_CMU_PLL_FRA2_GEN,    CMU_CLK_TYPE_PLL,   0,          CMU_CLK_24M,     1200    },
    [CMU_CLK_AXI0] =   {REG_CMU_CLK_AXI0,        CMU_CLK_TYPE_FDIV,  2,          CMU_CLK_CPU,     240     },
    [CMU_CLK_APB0] =   {REG_CMU_CLK_APB0,        CMU_CLK_TYPE_FDIV,  2,          CMU_CLK_AXI0,    120     },
    [CMU_CLK_CPU] =    {REG_CMU_CLK_CPU0,        CMU_CLK_TYPE_CPU,   15,         CMU_CLK_INT0,    480     },
    [CMU_CLK_PRE_DIV0]={REG_CMU_PRE_DIV,         CMU_CLK_TYPE_PWM,   5,          CMU_CLK_FRA0,    1200    },
    [CMU_CLK_PRE_DIV2]={0,                       CMU_CLK_TYPE_FDIV,  2,          CMU_CLK_AXI0,    120     }
};

//模块时钟配置
const cmu_mod_clk_t cmu_mod_clk[] __attribute__((aligned(16))) = {
                            //	REG_ADDR			      AUTH  RSTN  AHB	APB   AXI     SPEC_SRC		    SPEC2_SRC    SPEC_DIV   RES  SPEC_FMAX
	[CMU_MOD_DIS] =		      {REG_CMU_CLK_DIS,	            0,   0,    0, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_WDOG] =	      {REG_CMU_CLK_WDOG,	        1,   1,    0, 	0,     0, 	CMU_CLK_32K,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM0] =	      {REG_CMU_CLK_XPWM0,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM1] =	      {REG_CMU_CLK_XPWM1,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM2] =	      {REG_CMU_CLK_XPWM2,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM3] =	      {REG_CMU_CLK_XPWM3,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM4] =	      {REG_CMU_CLK_XPWM4,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PWM5] =	      {REG_CMU_CLK_XPWM5,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_DMA0] =	      {REG_CMU_CLK_DMA0,	        0,   1,    1, 	0,     1, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_DMA1] =	      {REG_CMU_CLK_DMA1,	        0,   1,    1, 	0,     1, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_DCE] =		      {REG_CMU_CLK_DCE,	            0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_CE] =		      {REG_CMU_CLK_CE,	            0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	200,},
	[CMU_MOD_USB_FS_DR] =	  {REG_CMU_CLK_USB_FS_DR,	    0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	48,	},
	[CMU_MOD_USB_FS_DR_PHY] = {REG_CMU_CLK_USB_FS_DR_PHY,   0,   1,    0,   0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	24,	},
	[CMU_MOD_EMAC] =	      {REG_CMU_CLK_EMAC,		    0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    0,	     0, 	50,	},
	[CMU_MOD_CANFD0] =	      {REG_CMU_CLK_CANFD0,	        0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	80,	},
	[CMU_MOD_CANFD1] =	      {REG_CMU_CLK_CANFD1,	        0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	80,	},
	[CMU_MOD_CAN0] =	      {REG_CMU_CLK_CAN0,	        0,   1,    0, 	2,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_XSPI] =	      {REG_CMU_CLK_XSPI,	        1,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    15,	     0, 	504,},
	[CMU_MOD_SPI0] =	      {REG_CMU_CLK_SPI0,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SPI1] =	      {REG_CMU_CLK_SPI1,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SPI2] =	      {REG_CMU_CLK_SPI2,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SPI3] =	      {REG_CMU_CLK_SPI3,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SPI4] =	      {REG_CMU_CLK_SPI4,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SPI5] =	      {REG_CMU_CLK_SPI5,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	266,},
	[CMU_MOD_SDMC0] =	      {REG_CMU_CLK_SDMC0,	        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    15,	     0, 	200,},
	[CMU_MOD_CORDIC] =	      {REG_CMU_CLK_CORDIC,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	200,},
	[CMU_MOD_HCL] =		      {REG_CMU_CLK_HCL,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	200,},
	[CMU_MOD_RDC] =		      {REG_CMU_CLK_RDC,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	200,},
	[CMU_MOD_PFM] =		      {REG_CMU_CLK_PFM,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	200,},
	[CMU_MOD_PBUS] =	      {REG_CMU_CLK_PBUS,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_FFT] =		      {REG_CMU_CLK_FFT,		        0,   1,    1, 	0,     1, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_SYSCFG] =	      {REG_CMU_CLK_SYSCFG,	        0,   0,    0, 	1,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	120,},
	[CMU_MOD_SPI_ENC] =	      {REG_CMU_CLK_SPIENC,	        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	180,},
	[CMU_MOD_PWMCS] =	      {REG_CMU_CLK_PWMCS,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	200,},
	[CMU_MOD_ADC] =		      {REG_CMU_CLK_PSADC,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	100,},
	[CMU_MOD_I2S0] =	      {REG_CMU_CLK_I2S0,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    63,	     0, 	25,	},
	[CMU_MOD_I2S1] =	      {REG_CMU_CLK_I2S1,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    63,	     0, 	25,	},
	[CMU_MOD_GPIO] =	      {REG_CMU_CLK_GPIO,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_UART0] =	      {REG_CMU_CLK_UART0,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART1] =	      {REG_CMU_CLK_UART1,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART2] =	      {REG_CMU_CLK_UART2,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART3] =	      {REG_CMU_CLK_UART3,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART4] =	      {REG_CMU_CLK_UART4,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART5] =	      {REG_CMU_CLK_UART5,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART6] =	      {REG_CMU_CLK_UART6,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART7] =	      {REG_CMU_CLK_UART7,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    31,	     0, 	60,	},
	[CMU_MOD_UART8] =	      {REG_CMU_CLK_UART8,		    0,   1,    0, 	1,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    7,	     0, 	60,	},
	[CMU_MOD_TA_IF] =	      {REG_CMU_CLK_TA_IF,		    0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	240,},
	[CMU_MOD_EDT_IF] =	      {REG_CMU_CLK_EDT_IF,	        0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	240,},
	[CMU_MOD_BISS_IF] =	      {REG_CMU_CLK_BISS_IF,	        0,   1,    1, 	0,     0, 	CMU_CLK_PRE_DIV0,	CMU_CLK_DIS,    7,	     0, 	240,},
	[CMU_MOD_SDFM] =	      {REG_CMU_CLK_SDFM,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	240,},
	[CMU_MOD_SID] =		      {REG_CMU_CLK_SID,		        0,   0,    0, 	2,     0, 	CMU_CLK_24M,		CMU_CLK_DIS,    0,	     0, 	24,	},
	[CMU_MOD_GTC] =		      {REG_CMU_CLK_GTC,		        0,   1,    0, 	2,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_I2C0] =	      {REG_CMU_CLK_TWI0,		    0,   1,    0, 	1,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	120,},
	[CMU_MOD_I2C1] =	      {REG_CMU_CLK_TWI1,		    0,   1,    0, 	1,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	120,},
	[CMU_MOD_I2C2] =	      {REG_CMU_CLK_TWI2,		    0,   1,    0, 	1,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	120,},
	[CMU_MOD_I2C3] =	      {REG_CMU_CLK_TWI3,		    0,   1,    0, 	1,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	120,},
	[CMU_MOD_THS] =		      {REG_CMU_CLK_THS,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_VS] =		      {REG_CMU_CLK_VS,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_CPM] =	          {REG_CMU_CLK_CPM,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_PGA] =		      {REG_CMU_CLK_PGA,		        0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_GPT0] =	      {REG_CMU_CLK_GPT0,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_GPT1] =	      {REG_CMU_CLK_GPT1,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_GPT2] =	      {REG_CMU_CLK_GPT2,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_GPT3] =	      {REG_CMU_CLK_GPT3,		    0,   1,    1, 	0,     0, 	CMU_CLK_DIS,		CMU_CLK_DIS,    0,	     0, 	0,	},
	[CMU_MOD_EtherCAT] =	  {REG_CMU_CLK_ESC,		        0,   1,    1, 	0,     0, 	CMU_CLK_FRA0,		CMU_CLK_DIS,    0,	     0, 	0,	},
};
